# Generated by Django 6.0.4 on 2026-04-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_insee', models.CharField(max_length=5, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('code_departement', models.CharField(max_length=3)),
                ('code_commune', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
