# Generated by Django 6.0.4 on 2026-04-15 21:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identifiant public pour les API')),
                ('code_postal', models.CharField(max_length=5)),
                ('date_mutation', models.DateField()),
                ('nature_mutation', models.CharField(choices=[('Vente', 'Vente'), ("Vente en l'état futur d'achèvement", "Vente en l'état futur d'achèvement"), ('Vente terrain à bâtir', 'Vente terrain à bâtir'), ('Echange', 'Echange'), ('Expropriation', 'Expropriation'), ('Adjudication', 'Adjudication')], max_length=60)),
                ('valeur_fonciere', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type_local', models.CharField(blank=True, choices=[('Maison', 'Maison'), ('Appartement', 'Appartement'), ('Dépendance', 'Dépendance'), ('Local industriel. commercial ou assimilé', 'Local industriel/commercial')], max_length=60)),
                ('surface_reelle_bati', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_pieces_principales', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nature_culture', models.CharField(blank=True, choices=[('T', 'Terre'), ('P', 'Pré'), ('V', 'Verger'), ('B', 'Bois'), ('L', 'Lande'), ('J', 'Jardin'), ('CA', 'Carrière'), ('E', 'Étang'), ('A', 'Autre')], max_length=2)),
                ('surface_terrain', models.PositiveIntegerField(blank=True, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='place.commune')),
            ],
            options={
                'ordering': ['-date_mutation'],
                'indexes': [models.Index(fields=['commune'], name='transaction_commune_71abce_idx'), models.Index(fields=['date_mutation'], name='transaction_date_mu_dfb34c_idx'), models.Index(fields=['type_local'], name='transaction_type_lo_bae0a4_idx')],
            },
        ),
    ]
