# Generated by Django 6.0.4 on 2026-04-16 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='venteparcelle',
            name='transaction_type_lo_bae0a4_idx',
        ),
        migrations.RenameField(
            model_name='venteparcelle',
            old_name='surface_reelle_bati',
            new_name='surface_bien_principal',
        ),
        migrations.AddField(
            model_name='venteparcelle',
            name='surface_totale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venteparcelle',
            name='types_locaux',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list),
        ),
        migrations.RemoveField(
            model_name='venteparcelle',
            name='type_local',
        ),
    ]
